# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f3259d237c6b44403a5e83da22925371d712c1254c0c96a6b2710a321012a67ac7aab32a1d1f64990293d45dab2ddf7672bdace008a72ff342669b0270e7ddb

test:
  secret_key_base: 3241d480a6da04b91d34a9b772704d15452b24405e4c5f3b69d93eefb1c16d5507e7a7f7d6d4d933bd1bb8378478bf7a6ade3421f30fa2c203165811f5d16f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
